kind: Deployment
apiVersion: apps/v1
metadata:
  name: mongodb-exporter
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-exporter
  template:
    metadata:
      labels:
        app: mongodb-exporter
    spec:
      containers:
        - name: mongodb-exporter
          image: docker.io/targetprocess/mongodb_exporter
          imagePullPolicy: Always
          args: ['-mongodb.uri', 'mongodb://admin:password@example-mongodb-svc']
          ports:
          - containerPort: 9001
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-exporter
  labels:
    app: mongodb-exporter
spec:
  ports:
  - port: 9001
    protocol: TCP
  selector:
    app: mongodb-exporter