kind: Deployment
apiVersion: apps/v1
metadata:
  name: mongodb-exporter
  namespace: default
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "9001"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-exporter
  template:
    metadata:
      labels:
        app: mongodb-exporter
    spec:
      containers:
        - name: mongodb-exporter
          image: docker.io/targetprocess/mongodb_exporter
          imagePullPolicy: Always
          args: ['-mongodb.uri', 'mongodb://admin:password@mongodb-exemplo-0.mongodb-exemplo-svc.default.svc.cluster.local:27017/admin?ssl=false']
          ports:
          - containerPort: 9001
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-exporter
  labels:
    app: mongodb-exporter
spec:
  ports:
    - name: http
      protocol: TCP
      port: 9001
      targetPort: 9001
  selector:
    app: mongodb-exporter