kind: Deployment
apiVersion: apps/v1
metadata:
  name: mongodb-exporter
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-exporter
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mongodb-exporter
    spec:
      containers:
        - name: mongodb-exporter
          image: docker.io/bitnami/mongodb-exporter
          args:
            - '--mongodb.uri'
            - >-
              mongodb+srv://admin:password@mongodb-exemplo-svc.default.svc.cluster.local/admin?ssl=false
            - '--mongodb.direct-connect=false'
            - '--compatible-mode'
          ports:
            - name: service
              containerPort: 9216
              protocol: TCP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mongodb-exporter
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-exporter
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mongodb-exporter
    spec:
      containers:
        - name: mongodb-exporter
          image: docker.io/bitnami/mongodb-exporter
          args:
            - '--mongodb.uri'
            - >-
              mongodb+srv://tarcisio:password@mongodb-exemplo-svc.default.svc.cluster.local/store?ssl=false
            - '--mongodb.direct-connect=false'
            - '--compatible-mode'
          ports:
            - name: service
              containerPort: 9216
              protocol: TCP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600