kind: Deployment
apiVersion: apps/v1
metadata:
  name: mongodb-exporter
  namespace: default
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "9216"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-exporter
  template:
    metadata:
      labels:
        app: mongodb-exporter
    spec:
      containers:
        - name: mongodb-exporter
          image: docker.io/bitnami/mongodb-exporter
          imagePullPolicy: Always
          args:
            - '--mongodb.uri'
            - 'mongodb://admin:password@mongodb-exemplo-svc/admin'
          ports:
          - containerPort: 9216
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
