apiVersion: v1
kind: Service
metadata:
  name: mongodb-exporter
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "9216"
spec:
  ports:
    - name: exporter
      protocol: TCP
      port: 9212
      targetPort: 9216
  selector:
    app: mongodb-exporter
  type: NodePort
  sessionAffinity: None
  type: ClusterIP
